In [2]:
import numpy as np

In [5]:
!pwd

/home/jovyan/multi_singer_transcription/MIR-1K/MIR-1K/PitchLabel


In [7]:
import os

In [9]:
files = os.listdir()

In [12]:
pitches = []
for file in files:
    try:
        pitches.append(np.loadtxt(file, dtype=float))
    except:
        print(file)

analyze_pitch_labels.ipynb
.ipynb_checkpoints


In [16]:
pitch_all = np.concatenate(pitches, axis=0 )

In [17]:
pitch_all.min()

0.0

In [18]:
pitch_all.max()

76.1935

In [19]:
pitch_all[pitch_all!= 0].min()

36.4027

In [31]:
np.round(pitch_all, 1).max()

76.2

In [22]:
np.histogram(pitch_all)

(array([118456,      0,      0,      0,     12,   8854,  68355, 118353,
         78043,   6783]),
 array([ 0.     ,  7.61935, 15.2387 , 22.85805, 30.4774 , 38.09675,
        45.7161 , 53.33545, 60.9548 , 68.57415, 76.1935 ]))

In [29]:

76.19-36.4

39.79

In [34]:
(76.2-36.4)/0.05

796.0

In [24]:
(76.19-36.4)/12

3.3158333333333334

In [25]:
76.19/12

6.349166666666666

In [26]:
def semitone_to_pitch(semitones, ref_frequency=440):
    """
    Convert semitones to fundamental frequency (Hz).

    Parameters:
        semitones (float or array-like): Pitch values in semitones.
        ref_frequency (float): Reference frequency (Hz). Default is A4 at 440 Hz.

    Returns:
        float or array-like: Fundamental frequency or array of fundamental frequencies.
    """
    frequency = ref_frequency * 2 ** (semitones / 12)
    return frequency

    # # Calculate the semitone difference
    # semitone_diff = 12 * np.log2(frequency / ref_frequency)
    
    # # Define the mapping of semitone differences to note names
    # note_names = ['C', 'C#', 'D', 'D#', 'E', 'F', 'F#', 'G', 'G#', 'A', 'A#', 'B']
    
    # # Calculate the octave number
    # octave = 4 + semitone_diff / 12
    
    # # Calculate the index within the note_names list
    # note_index = int(round(semitone_diff % 12))

In [37]:
semitone_to_pitch(47.7627, ref_frequency=440)

6944.161153474553

In [28]:
semitone_to_pitch(36.4, ref_frequency=440)

3602.276099828647

In [41]:
lengths = []
for i in pitches:
    lengths.append(i.shape[0])

In [47]:
np.median(lengths)

379.0

In [46]:
np.histogram(lengths)

(array([  3,   8,  49, 219, 204, 156, 111,  94,  87,  69]),
 array([152. , 196.8, 241.6, 286.4, 331.2, 376. , 420.8, 465.6, 510.4,
        555.2, 600. ]))